# This file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/
sudo: required

language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version
    - coverage3 --version
    - python3 -c "import numpy; print(numpy.__version__)"
    
env:
    - TRAVIS_CACHE=/home/travis/jrwall11/cs373-netflix/cache_files
    
script:
    - date
    - ls -al
    - touch Netflix.log
    - git clone https://github.com/cs373-summer-2015/netflix-tests.git cache_files
    - pwd cache_files
    - ls -al
    - make Netflix.html
    - ls -al
    - make test
    - ls -al
    - make check
